### ISSUE TITLE
ImportError: DLL load failed while importing defs:

### ISSUE THREAD

**Issue by SaaSGun** [tianyikillua/medcoupling#7]
Operating System: Windows 10
Python version: 3.11
Where Python was acquired: Anaconda on Windows
h5py version: 3.11.0
HDF5 version: None

My script is as follows:

`
import medcoupling
`
`
import h5py
`

The full traceback/stack trace shown: ImportError:

Traceback (most recent call last):
  File "m:\named_selections\trial.py", line 2, in <module>
    import h5py
  File "M:\named_selections\.conda\Lib\site-packages\h5py\__init__.py", line 33, in <module>
    from . import version
  File "M:\named_selections\.conda\Lib\site-packages\h5py\version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py\\h5.pyx", line 1, in init h5py.h5
ImportError: DLL load failed while importing defs: The specified procedure could not be found.

Describe: Hi, I am using medcoupling together with h5py
Installed medcoupling using -> conda install conda-forge::medcoupling
Installed h5py using -> conda install conda-forge::h5py

Could someone help me with this error please. thanks

**Comment by tianyikillua** [comment]
@SaaSGun Hi, the medcoupling PyPI package is now maintained by @jschueller. Maybe he can lend a hand?

**Comment by SaaSGun** [comment]
@tianyikillua - thankyou for your response. Waiting to hear from @jschueller!

**Comment by SaaSGun** [comment]
So basically, taking following steps helped solve my issue -

started with a clean conda virtual environment
ran the following:
conda install conda-forge::meshio
conda install conda-forge::medcoupling
pip install --no-deps pymapping (make sure pymapping does get installed in the virtual env and not in the base environment)

**Comment by jschueller** [comment]
make sure you're not mixing packages from conda-forge and defaults (use miniforge)
anyway its not related to our pypi packages
